name: Tag mo-fmt

on:
  push:
    branches:
      - main
    paths:
      - packages/mo-fmt/package.json
    
  workflow_dispatch:

jobs:
  tag-release:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: create-tag
        run: RELEASE_TAG=v$(node -e "console.log(require('./packages/mo-fmt/package.json').version)") && git tag $RELEASE_TAG && git push origin $RELEASE_TAG
        continue-on-error: true
    outputs:
      - tag-outcome: ${{ steps.create-tag.outcome }}
  release:
    needs: [tag-release]
    uses: ./.github/workflows/Release.yml
    secrets: inherit
    if: needs.tag-release.outputs.tag-outcome == 'success'
